### ISSUE TITLE
Every view shows empty

### ISSUE THREAD

**Issue by ChubiPanda** [EskiMojo14/keycaplendar#3]
All the views regardless of search parameters show empty.

**Comment by EskiMojo14** [comment]
I've experienced this myself, but can't reliably replicate.

When researching, it appears this error is caused by the site not forming a stable enough connection to the database. Unsure how to fix.

The site currently pulls all sets once from the database. Reworking this so that only sets relevant to the current page are pulled may prevent this issue, as the amount of data to pull would be smaller. However, this would be a large rework of how the site handles data.

**Comment by EskiMojo14** [comment]
It's worth noting that a refresh of the page usually fixes the issue.

**Comment by ChubiPanda** [comment]
Refresh worked for me too.  How odd. Othewise it a great site!
